#!/bin/sh

pwd=`pwd`
FILES=('.gitconfig' '.screenrc' '.zshrc')
CONFIG_DIR="$HOME/.basic_config"
CP="/bin/cp"

cd "$HOME"
rm -r "$CONFIG_DIR"
git clone http://github.com/arthurdarcet/dotfiles.git "$CONFIG_DIR"

cd "$CONFIG_DIR"

for i in "${FILES[@]}"
do
    doit=1
    if [ -f "$HOME/$i" ]; then
        git diff -- "$HOME/$i" "$i"
        ret=$?
        if [ "$ret" != "0" ]; then
            echo "$(tput setaf 3)$i modified, apply ?$(tput sgr0) [y/N]"
            read rep
            doit=`[ "$rep" == "y" ] && echo 1 || echo 0`
        fi
    fi
    if [ "$doit" == "1" ]; then
        # --parents copy "a/b/c" into $HOME/a/b/c
        cp --parents "$i" "$HOME/"
    fi
done

cd "$pwd"
